// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZKL1SuJnOLBoDQMrULXQi8AgomJjn-qc',
    appId: '1:889447214349:web:611a231a05702113735444',
    messagingSenderId: '889447214349',
    projectId: 'my-audio-story-app',
    authDomain: 'my-audio-story-app.firebaseapp.com',
    storageBucket: 'my-audio-story-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmTKuhpareST4SyYGTSkYu_j_MJvCy80',
    appId: '1:889447214349:android:d00825d71ef6044c735444',
    messagingSenderId: '889447214349',
    projectId: 'my-audio-story-app',
    storageBucket: 'my-audio-story-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgjOMPKVoAuSR1Oi4vcgWpzR-UO7eFsoA',
    appId: '1:889447214349:ios:971f68a27ca64876735444',
    messagingSenderId: '889447214349',
    projectId: 'my-audio-story-app',
    storageBucket: 'my-audio-story-app.firebasestorage.app',
    iosBundleId: 'com.example.audioStoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgjOMPKVoAuSR1Oi4vcgWpzR-UO7eFsoA',
    appId: '1:889447214349:ios:971f68a27ca64876735444',
    messagingSenderId: '889447214349',
    projectId: 'my-audio-story-app',
    storageBucket: 'my-audio-story-app.firebasestorage.app',
    iosBundleId: 'com.example.audioStoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZKL1SuJnOLBoDQMrULXQi8AgomJjn-qc',
    appId: '1:889447214349:web:a5710fbf63f0517b735444',
    messagingSenderId: '889447214349',
    projectId: 'my-audio-story-app',
    authDomain: 'my-audio-story-app.firebaseapp.com',
    storageBucket: 'my-audio-story-app.firebasestorage.app',
  );
}
